### PR TITLE
UISP Submission Deadline Extension

### PR DESCRIPTION
**Pull request by rgfreedman**
Extended UISP Workshop Deadline

### CODE REVIEW

**Review by ronwalf — CHANGES_REQUESTED** [review]
It looks like you added the autogenerated 'serve' directory.  I'll what I can parse out of this.

**Comment by rgfreedman** [comment]
My apologies.  I never used Git or Jekyll before.  So I was trying everything after downloading to get both to work.  Would it be easier to re-clone and try again?

**Comment by ronwalf** [comment]
I believe I managed to incorporate your changes (independent of this pull request).  Re-cloning and trying again is drastic, but it would work.  I only gave instructions on how to create the initial pull request, but not how to make more, so here's my attempt at fixing that for the future:

### Set up a remote tracking branch ###
After you've cloned the ICAPS on GitHub and set it up on your local machine,  you should add a remote repository for tracking changes to the main site:
 ```
$ git remote add icaps git@github.com:ICAPS2017/icaps2017.github.io.git
```
You only need to do this once for your local repository.

### Branch to make your edits ###
Use git-fetch to update the remote repository, and then create a new branch for the pull request you plan to make:
```
$ git fetch icaps
$ git checkout -b <branch-name> icaps/master
```
Edit your files normally.  If you add a new file, remember to add it with `git add <path-to-new-file>`.  Commit your changes with `git commit -am <useful but terse change description>`,  and push it back to GitHub with `git push origin/<branch-name>':
```
$ git add <path-to-new-file>
$ git commit -am <useful but terse change description>
$ git push origin
```
You should repeat this part of the procedure for each new pull request.

**Comment by rgfreedman** [comment]
Understood.  Thank you very much for fixing it and the instructions for next time.

**Pull request closed without merging**
